/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author valentin
 */
public class FormulaireBalsamiq extends javax.swing.JFrame {

    /**
     * Creates new form IHM_Balsamiq
     */
    public FormulaireBalsamiq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        civ = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        subHeaderLabel = new javax.swing.JLabel();
        beforeFormLabel = new javax.swing.JLabel();
        civFormLabel = new javax.swing.JLabel();
        lastnameFormLabel = new javax.swing.JLabel();
        firstnameFormLabel = new javax.swing.JLabel();
        mailFormLabel = new javax.swing.JLabel();
        mobileFormLabel = new javax.swing.JLabel();
        fixFormLabel = new javax.swing.JLabel();
        contactFormLabel = new javax.swing.JLabel();
        afterFormLabel = new javax.swing.JLabel();
        fixField = new javax.swing.JTextField();
        mobileField = new javax.swing.JTextField();
        mailField = new javax.swing.JTextField();
        firstnameField = new javax.swing.JTextField();
        lastnameField = new javax.swing.JTextField();
        civRadioMale = new javax.swing.JRadioButton();
        civRadioFemale = new javax.swing.JRadioButton();
        registerButton = new javax.swing.JButton();
        informationLabel = new javax.swing.JLabel();
        contactComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shop'IHM");
        setAutoRequestFocus(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        headerLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Bienvenue sur Shop'IHM");

        subHeaderLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        subHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subHeaderLabel.setText("L'inscription est gratuite !");

        beforeFormLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        beforeFormLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        beforeFormLabel.setText("Complétez le formulaire ci-dessous puis cliquez sur \"M'inscrire\" pour nous rejoindre");

        civFormLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        civFormLabel.setText("Civilité:");

        lastnameFormLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lastnameFormLabel.setText("Nom:");

        firstnameFormLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        firstnameFormLabel.setText("Prénom:");

        mailFormLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mailFormLabel.setText("Courriel:");

        mobileFormLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mobileFormLabel.setText("Téléphone (Mobile):");

        fixFormLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fixFormLabel.setText("Téléphone (Fixe):");

        contactFormLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        contactFormLabel.setText("Préférence de contact*:");

        afterFormLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        afterFormLabel.setText("En cliquant sur le bouton \"M'inscrire\", vous acceptez nos conditions générales");

        fixField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mobileField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        firstnameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lastnameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lastnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameFieldActionPerformed(evt);
            }
        });

        civRadioMale.setBackground(new java.awt.Color(255, 255, 255));
        civ.add(civRadioMale);
        civRadioMale.setSelected(true);
        civRadioMale.setText("Monsieur");
        civRadioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civRadioMaleActionPerformed(evt);
            }
        });

        civRadioFemale.setBackground(new java.awt.Color(255, 255, 255));
        civ.add(civRadioFemale);
        civRadioFemale.setText("Madame");

        registerButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        registerButton.setText("M'inscrire");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        informationLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        informationLabel.setText("* Coordonnées utilisées pour la confirmation de votre compte et le suivi de commande");

        contactComboBox.setBackground(new java.awt.Color(255, 255, 255));
        contactComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        contactComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Courriel", "Téléphone (Mobile)" }));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(subHeaderLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(beforeFormLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(afterFormLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(lastnameFormLabel)
                                .addGap(117, 117, 117)
                                .addComponent(lastnameField))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(firstnameFormLabel)
                                .addGap(100, 100, 100)
                                .addComponent(firstnameField))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(mailFormLabel)
                                .addGap(99, 99, 99)
                                .addComponent(mailField))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(mobileFormLabel)
                                .addGap(33, 33, 33)
                                .addComponent(mobileField))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(fixFormLabel)
                                .addGap(48, 48, 48)
                                .addComponent(fixField))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(civFormLabel)
                                .addGap(107, 107, 107)
                                .addComponent(civRadioMale)
                                .addGap(18, 18, 18)
                                .addComponent(civRadioFemale)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(contactFormLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contactComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(153, 153, 153))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(informationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(561, Short.MAX_VALUE)
                .addComponent(registerButton)
                .addGap(157, 157, 157))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beforeFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(civFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(civRadioMale)
                    .addComponent(civRadioFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fixFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fixField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(afterFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(informationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String firstName = firstnameField.getText();
        String lastName = lastnameField.getText();
        String civAsText = civRadioMale.isSelected() ? "M." : "Mme";
        String conditionnalText = contactComboBox.getSelectedItem().toString().equalsIgnoreCase("Téléphone (Mobile)") ? "un SMS au\n" + mobileField.getText() : "un courriel sur votre\nboîte " + mailField.getText();

        JOptionPane.showMessageDialog(null, "Merci pour votre inscription " + civAsText + " " + firstName + " " + lastName + " !\nVous recevrez dans quelques instants " + conditionnalText + " pour finaliser votre inscription.", "Un peu de patience...", JOptionPane.INFORMATION_MESSAGE);
        
        firstnameField.setText("");
        lastnameField.setText("");
        mailField.setText("");
        mobileField.setText("");
        fixField.setText("");
        civRadioMale.setSelected(true);
        contactComboBox.setSelectedItem("Courriel");
    }//GEN-LAST:event_registerButtonActionPerformed

    private void civRadioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civRadioMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_civRadioMaleActionPerformed

    private void lastnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaireBalsamiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaireBalsamiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaireBalsamiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaireBalsamiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulaireBalsamiq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afterFormLabel;
    private javax.swing.JLabel beforeFormLabel;
    private javax.swing.ButtonGroup civ;
    private javax.swing.JLabel civFormLabel;
    private javax.swing.JRadioButton civRadioFemale;
    private javax.swing.JRadioButton civRadioMale;
    private javax.swing.JComboBox<String> contactComboBox;
    private javax.swing.JLabel contactFormLabel;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel firstnameFormLabel;
    private javax.swing.JTextField fixField;
    private javax.swing.JLabel fixFormLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JLabel lastnameFormLabel;
    private javax.swing.JTextField mailField;
    private javax.swing.JLabel mailFormLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField mobileField;
    private javax.swing.JLabel mobileFormLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel subHeaderLabel;
    // End of variables declaration//GEN-END:variables
}
